/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    paintings: Painting;
    'journal-posts': JournalPost;
    'social-posts': SocialPost;
    'commissioned-portraits': CommissionedPortrait;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    paintings: PaintingsSelect<false> | PaintingsSelect<true>;
    'journal-posts': JournalPostsSelect<false> | JournalPostsSelect<true>;
    'social-posts': SocialPostsSelect<false> | SocialPostsSelect<true>;
    'commissioned-portraits': CommissionedPortraitsSelect<false> | CommissionedPortraitsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and SEO. Bulk uploads are automatically filled from the filename; edit this after upload when needed.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Original paintings for sale in the gallery.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paintings".
 */
export interface Painting {
  id: number;
  title: string;
  /**
   * URL-friendly identifier. Lowercase, dashes instead of spaces (e.g. red-fox-in-winter).
   */
  slug: string;
  /**
   * The specific animal or main subject — e.g. Red fox
   */
  subject?: string | null;
  /**
   * Used for gallery filters and homepage collection blocks. Pasture = farm + horse; The Wild = wild + bird; Small Wonders = other.
   */
  subjectGroup?: ('dog' | 'cat' | 'horse' | 'farm' | 'wild' | 'bird' | 'other') | null;
  /**
   * Part of a named series? Budderlee paintings get their own page at /budderlee with character name and role.
   */
  collection?: ('none' | 'meadowbrook') | null;
  /**
   * e.g. Maisie
   */
  characterName?: string | null;
  /**
   * e.g. The Pie Maker
   */
  characterRole?: string | null;
  year: number;
  medium: string;
  widthIn: number;
  heightIn: number;
  /**
   * Price in cents. $1,450 = 145000
   */
  priceCents: number;
  /**
   * Determines the shipping rate charged at checkout
   */
  sizeTier: 'free' | 'small' | 'medium' | 'large' | 'oversize';
  /**
   * Short gallery/card description. Keep this concise; use the story field below for the longer piece-specific narrative.
   */
  description: string;
  /**
   * Optional longer story shown on the artwork detail page. Leave blank to use the default Barbara/expressive-realism copy.
   */
  storyBehindPainting?: string | null;
  /**
   * Giclée print sizes offered for this painting. Leave empty if prints are not (yet) available. Prints stay purchasable after the original sells.
   */
  printOptions?:
    | {
        widthIn: number;
        heightIn: number;
        /**
         * $75 = 7500
         */
        priceCents: number;
        id?: string | null;
      }[]
    | null;
  images: {
    image: number | Media;
    id?: string | null;
  }[];
  /**
   * Show on the home page
   */
  featured?: boolean | null;
  /**
   * Hide the Buy button and show a sold badge
   */
  sold?: boolean | null;
  /**
   * Tick and save to post this painting to Instagram + Facebook (via Ayrshare). Posts once, when first ticked; the delivery report appears under Social Posts. Untick and re-tick to announce again.
   */
  announceOnSocial?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Notes from the studio. Published posts appear under /blog.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-posts".
 */
export interface JournalPost {
  id: number;
  title: string;
  /**
   * URL-friendly identifier. Used in /blog/[slug].
   */
  slug: string;
  /**
   * One or two sentences shown on the journal index page
   */
  excerpt?: string | null;
  cover?: (number | null) | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  status: 'draft' | 'published';
  /**
   * Shown as the post date on the journal
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Compose once, post everywhere. Set status to “Send” and save — the post goes out now, or at the scheduled time if one is set. Auto-announced paintings appear here too, as a record.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-posts".
 */
export interface SocialPost {
  id: number;
  /**
   * Internal label — not part of the post. e.g. “Maisie arrival announcement”
   */
  title: string;
  /**
   * The post text. Keep under 280 characters if X is selected — longer text is truncated there.
   */
  message: string;
  /**
   * Optional image. Instagram and Pinterest require one.
   */
  image?: (number | null) | Media;
  /**
   * Which connected accounts to post to. Accounts are linked in the Ayrshare dashboard.
   */
  platforms?: ('instagram' | 'facebook' | 'twitter' | 'pinterest')[] | null;
  /**
   * Leave empty to post immediately when sent. Set a future date/time for a timed release.
   */
  scheduleAt?: string | null;
  /**
   * Set to “Send” and save to deliver. It becomes Posted (or Scheduled), or Failed with the reason below. To retry after a failure, fix the issue and set “Send” again.
   */
  status: 'draft' | 'send' | 'scheduled' | 'posted' | 'failed';
  /**
   * Delivery report from the last send attempt.
   */
  result?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Finished commissions shown on the commissions page, newest first. Add the portrait photo(s) and what the owner said about it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commissioned-portraits".
 */
export interface CommissionedPortrait {
  id: number;
  /**
   * e.g. Wally in the Garden
   */
  title: string;
  /**
   * e.g. Golden Retriever, or the pet's name and breed
   */
  subject?: string | null;
  /**
   * Year painted
   */
  year?: number | null;
  medium?: string | null;
  widthIn?: number | null;
  heightIn?: number | null;
  /**
   * First image is the one shown on the commissions page. A photo of the portrait in the owner's home works beautifully.
   */
  images: {
    image: number | Media;
    id?: string | null;
  }[];
  /**
   * What the owner said when they received it, in their words. Shown as a quote under the portrait.
   */
  ownerQuote?: string | null;
  /**
   * How they'd like to be credited, e.g. Sarah M.
   */
  ownerName?: string | null;
  /**
   * e.g. Burlington, Vermont
   */
  ownerLocation?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'paintings';
        value: number | Painting;
      } | null)
    | ({
        relationTo: 'journal-posts';
        value: number | JournalPost;
      } | null)
    | ({
        relationTo: 'social-posts';
        value: number | SocialPost;
      } | null)
    | ({
        relationTo: 'commissioned-portraits';
        value: number | CommissionedPortrait;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paintings_select".
 */
export interface PaintingsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subject?: T;
  subjectGroup?: T;
  collection?: T;
  characterName?: T;
  characterRole?: T;
  year?: T;
  medium?: T;
  widthIn?: T;
  heightIn?: T;
  priceCents?: T;
  sizeTier?: T;
  description?: T;
  storyBehindPainting?: T;
  printOptions?:
    | T
    | {
        widthIn?: T;
        heightIn?: T;
        priceCents?: T;
        id?: T;
      };
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  featured?: T;
  sold?: T;
  announceOnSocial?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-posts_select".
 */
export interface JournalPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  cover?: T;
  body?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-posts_select".
 */
export interface SocialPostsSelect<T extends boolean = true> {
  title?: T;
  message?: T;
  image?: T;
  platforms?: T;
  scheduleAt?: T;
  status?: T;
  result?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commissioned-portraits_select".
 */
export interface CommissionedPortraitsSelect<T extends boolean = true> {
  title?: T;
  subject?: T;
  year?: T;
  medium?: T;
  widthIn?: T;
  heightIn?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  ownerQuote?: T;
  ownerName?: T;
  ownerLocation?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}